jobs:
  include:
  - language: node_js
    node_js:
    - 10.15.0
    services:
    - docker
    cache:
      yarn: true
    before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
    - export PATH=$HOME/.yarn/bin:$PATH
    install:
    - yarn install --frozen-lockfile
    script:
    - yarn run lint
    - yarn workspace @cedalo/machine-core test
    - yarn workspace @cedalo/graphql test
    - yarn workspace @cedalo/webui run local-build
    deploy:
    - provider: script
      script: bash -c "docker login -u $DOCKER_USER -p $DOCKER_PASSWORD && node scripts/deploy.js
        --push --derivative dev --tag develop"
      on:
        branch: master
      skip_cleanup: true
    - provider: script
      script: bash -c 'docker login -u $DOCKER_USER -p $DOCKER_PASSWORD && node scripts/deploy.js
        --push --tag $TRAVIS_TAG'
      on:
        condition: "${TRAVIS_TAG} =~ ^[0-9]+\\.[0-9]+(\\.[0-9]+)?(-rc[0-9]+)?(-bugfix[0-9])?$"
        tags: true
      skip_cleanup: true
notifications:
  slack:
    secure: IclZ9eaz/bfq6LfRSzCddkYOWM2Bp5stp6z/AsEjF7YasCaAX5nnRSxbNpyLUKdoLJ8QBm5oEIF7JltVUNnFOT3XSJ8OBaZ93xg7LJnGF2dDCNnjxkrdCPC3szT3/8NpXKNfbKyxSWwDr61flP5Tkr1MYSVCa4tsZrYkjyu3pJbQDsTg4jB3bAu7W/JvxD+m99wK+LyDhELQk6m3rcuZs5UOJn3WBIayXBZJYo5AFgDqxbst+XFZus+bWAZXFoIetX9n3ri8qEwSiMkp34YqyCvpim+YhNgSzxRrfjsZ4qMnyzmjP0a9NcGD4bVt5AzDKH3nGd9Lo3FtlL2ZvgyZPaFLE00HvqOPZqGD+EUKbX7iDwdMkJNP3b+vYJFUAW7dcTKRa4P7e95qpkFBD28PIxxoWNabHLZ+4odkmbe05tI/rOWlyP1Lunj1zrNE72eqv5OJFiVx7xmiSOlCoabnB065qO7xFyhNDEhMba3YZGPkmLMRdUuQlfHYO1gAtepmlB7OfGDiQuYm5XjehCa5p882THx1ItWyRBsxkfb4JSSr3qBQByCKs8doHvYrIhbAnM6PBB5ET+jRkwAF+MwRnsE6brJWy4rsLnmp50H4NS9KsfFLr7JemU4lz6EtrM6WvcPGblZ3yxOpvCfGTjI5UfJINIVU8c0ug8xH69YJP94=
env:
  global:
  - secure: F2BIf5rzkNeHZ4M2tbAR/s00JXKc6UJLcg0eyL3jYET4BOEAxS9e+2x07sfJJH7AUiCqvEZjO6VwwogmkW/T7oMJio79IOJP0ZedvDVn27+YiXrUoyJZ6MLcgC5bQP1p3ueZ6bsBM7EztDs800DMAXHrqBKTWWiNFvmg99OjP9hIehUL22Is0nrPlf0zPxbtR6LPI6wErR4ED1jvpf7sO4EHo2gDKTIM/+Og+INHf0XEWlFBgyWlk9K1cUJQacsGNAKUcCgwLHkmYnANmBbMDZLGQN0UbdmlS4uQNCyeRGVGqF6uDL6e26vXThKGdSGxGYuMLhwiLuvL3PzWWIMGDiY4JQyJteU42kiQe/1v/uPi6E57NBqF9OazRb3TuC60lGZKBq7tCG1wu4LSgqzmZbm7vPlVrpfX2oc/Ge8PUem0HD9uM4rSK2fnrUjtELv1CEQPYY8O9DL/N/TyuGeG2uYyKOhNcFfyZv4lESX7FKT//7WzFpFQlu5lerQInG2BRWj/r5uqPu72lP4CAdpSTIo+cWP3uJo74vC64aaiKANViYbqxSpJzmIcDzHH258PHBPx10BGkgiRxz8YBQ87fvHcWPVSHNsCyRvwutE3UTFU4JnLCwr+/JtTK+++5617vNmgUJ1P7W86A4nmZwDY3UUf35HBFQnH3AQzW7PDYnI=
  - secure: bVeP83oXXrfh59sJUAl63zLpEMI40g1iLUBfq3bcDEiRn5jBXcj1DeQA4YdozgaC57ZD3V80jsRS0NW5i6pZ5eAaNvZArfXU7cYJ2a0dLlbnZ6+YeyYIH1v/3mB7iKYeJa6ptjEg2NBvHj+3lbFMYgLXz1c9cxawz2c0Nv1PIi7Ije+btJTfSIY6WbG3ytNJ5GneXIOZL5ULv9DzFeVK4lCZ1siMqJoSiFhoqWf7bjFt9dtSqe/mCGBlBKeVpxkrDGnZZW4KFk1SQEinu6xvDNhHuLzOsewBC/P0IYW/aXbrIabB/ERN/925PvEJwFq/IroR4EBaIlve+JvQ2YIx9rDOxlMf4jGPV12wdLVuNEf681YapdVQE8zr/CSZUaer+qhvlKZtS6w8o8ZvcZXpD+Awkjz1Fzhcq5tYug2v2ZDPdM4JTQhooRoy7fJEphJUkjAxHlDr+iYZKbuFk7EBrfrVjmKGThI3cCXMaScyaAW+XiuAPNH8OvBxR9esfYLtvtnBIqb8LjxHyusxImX8rEqlEmgzUBLyvoXrhp1guM6uUwgrfr92Tma8gZ/3Gm+YMXhssufwExzz7s33rXdbbfcr86J1ime0cnY2cNgJu5R1Q4miekQg83IBl/gLr+aq3HD1DejwBpcXbWIXgdiLR52hP/Af29QleXAsX/aL4HI=
