jobs:
  include:
  - language: node_js
    node_js:
    - 10.15.0
    services:
    - docker
    cache:
      yarn: true
    before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
    - export PATH=$HOME/.yarn/bin:$PATH
    install:
    - yarn install --frozen-lockfile
    script:
    - yarn run lint
    - yarn workspace @cedalo/machine-core test
    - yarn workspace @cedalo/graphql test
    - yarn workspace @cedalo/webui run local-build
    deploy:
    - provider: script
      script: bash -c "docker login -u $DOCKER_USER -p $DOCKER_PASSWORD && node scripts/deploy.js
        --push --derivative dev --tag develop"
      on:
        branch: master
      skip_cleanup: true
    - provider: script
      script: bash -c 'docker login -u $DOCKER_USER -p $DOCKER_PASSWORD && node scripts/deploy.js
        --push --tag $TRAVIS_TAG'
      on:
        condition: "${TRAVIS_TAG} =~ ^[0-9]+\\.[0-9]+(\\.[0-9]+)?(-rc[0-9]+)?(-bugfix[0-9])?$"
        tags: true
      skip_cleanup: true
notifications:
  slack:
    secure: IclZ9eaz/bfq6LfRSzCddkYOWM2Bp5stp6z/AsEjF7YasCaAX5nnRSxbNpyLUKdoLJ8QBm5oEIF7JltVUNnFOT3XSJ8OBaZ93xg7LJnGF2dDCNnjxkrdCPC3szT3/8NpXKNfbKyxSWwDr61flP5Tkr1MYSVCa4tsZrYkjyu3pJbQDsTg4jB3bAu7W/JvxD+m99wK+LyDhELQk6m3rcuZs5UOJn3WBIayXBZJYo5AFgDqxbst+XFZus+bWAZXFoIetX9n3ri8qEwSiMkp34YqyCvpim+YhNgSzxRrfjsZ4qMnyzmjP0a9NcGD4bVt5AzDKH3nGd9Lo3FtlL2ZvgyZPaFLE00HvqOPZqGD+EUKbX7iDwdMkJNP3b+vYJFUAW7dcTKRa4P7e95qpkFBD28PIxxoWNabHLZ+4odkmbe05tI/rOWlyP1Lunj1zrNE72eqv5OJFiVx7xmiSOlCoabnB065qO7xFyhNDEhMba3YZGPkmLMRdUuQlfHYO1gAtepmlB7OfGDiQuYm5XjehCa5p882THx1ItWyRBsxkfb4JSSr3qBQByCKs8doHvYrIhbAnM6PBB5ET+jRkwAF+MwRnsE6brJWy4rsLnmp50H4NS9KsfFLr7JemU4lz6EtrM6WvcPGblZ3yxOpvCfGTjI5UfJINIVU8c0ug8xH69YJP94=
env:
  global:
  - secure: Hy8JruNI848zSHa8ziHjDcAfJBFUEIKxWuxlnrBtR8KjbbACtnDCTYBMatVQlx4uYuGKpCxBuPWcTnIF0E5l/63SskVBVWwas6RNUKU+4RFU+NBmcM0EwrKRySGPh2yp5Hw0afIckQNiLoZnPcQmiC8Lt7rjw/m78/aS2aV529yT/ibANdF8qRf6tltulCHo30RAzl7TXh/pG5o1ELWL7p8upVBsUJHq0gdmk6Mm7zmOLpsNrgw7D87y1NcLK6DeFFr4DCMNSFXcfdNFajMzj7Jxr6vNc/7Yusl43Z/p06MmpbOejb8Y0RYl8ta9E0rSfv4pjcB3pxbI4BVgtluDok5gIT+224x2OAB0ej4qndA6IiYuXk5Xv2JZSLWFkO4LdZsZE3Vx2fxPd5teR/5f6QR/jyN1bTQIifa3JcEaROopF+27U5Vvw52uCasli8MFiRzMqJTQTIVNo1Jh/Zw5j+vaneZpWrg0ohNGDXhzYS5WYA5S7ZCkForfZzRQqjgjhPrZQLwoqhK7sBK+vr7yRXFa+MgrQBQsRsWwJ6Mm9ZT+6xL+Xe3/jdxas5OSkv1T9dENjwj3Bi9f5o8mpU5hHDH5Me+YeuuUcbAO8oQePHVlaQLZTECQMn4oyu1LVkwgLx89hPnOwA82GTKXZJdlLv+aGNECF+kDg9+kCoimOY8=
  - secure: ZCMZEGOUT+BfhoKYbkmCciMD0VaQLu0XxOiLrs+rsmLvUsBMYF8R3L/WcEa9ySNiWzeGRynjFYhCTSK1Kdn2/iUGVcr02B4EPGGt9rYZd8Yx+2XAxbZ+1+soJdISVvwZWKUwDGyBGQd7mGrsQJKHsYT/uDFyvr/JbDjcuP+Ilq3/wZyryyOzHIbk3IluAGQCaS3S0XZozs1JmRrR9HFJvkrTD/4gzkSgN87sJTLlFqI1SCL3HpWaPL2b7+kkBj/isSmeJ+7aHdTi5DqFW9vpbWhQ4xIHlhh4zhqTI2V5PkdB9QguE5N8ULcoEOom4FR2UFRI1K0T3JX7SizOhcwvUp2cCxnQGOTXKp4i2ss3IFKvjRX+P3aHpgzYu4gUMkQspNA+ex6zPzwkqLsIqo8qyplUkoyFVkOPUp9jA8E+45vZONwdhjKlE40+k/79OsRPQmcrmjzUjN+OfUnnxUQqXX0BvPrMAaYaZZoDxCSFABAj3FnbQqu9Xs+Sfwy+eTOLqzla7y1GcbLQtQsHCX3A+X/LWG24YdqCbYvJmGUQyVWdE5xit0lPVbDZ0/OA5C+d11ZVgvLbFd8EMP4x5YN0ZZZ3xTqY3/bLyTnmUcaTy5FbpVB/pIpqRc81RSPqkUOyGn9J9XVm7ck0hf9NlpnyHMxoW2MddEkLWwinym3YJQE=
