version: '3.7'

services:
  streamsheets:
    image: cedalo/streamsheets-personal:1.5
    container_name: streamsheets
    ports:
      - 8081:8081
      - 8083:8083
      - 1884:1884
      - 6379:6379
    expose:
      - 8081
      - 8083
    volumes:
      - ../settings/mosquitto:/etc/mosquitto-default-credentials
    networks:
      - streamsheets
    # logging:
    #   driver: "none"
networks:
  streamsheets:
    name: streamsheets
    driver: bridge
